name: Build & Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fix Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: .
        run: pip3 install -r app/requirements.txt

      - name: Run Unit Tests
        working-directory: app
        run: python3 -m pytest
